"""Refresh generated module/metadata blocks in the self-contained review UI.

Edit ray-tracing.js, pareto.js, pareto-view.js, and ray-indices-fixture.json
as their source of truth. This command copies them into the inline preview
without a network dependency. The desktop build loads the same JS modules
as separate local assets.
"""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]


def sync():
    fragment = ROOT / "design/optics-workspace-concept.html"
    source = fragment.read_text(encoding="utf-8")
    module = (ROOT / "design/ray-tracing.js").read_text(encoding="utf-8")
    if "</script" in module.lower():
        raise ValueError("Ray module cannot contain an inline script terminator")
    replacement = '<script data-optics-module="ray-tracing">\n// Generated by scripts/sync_preview_modules.py.\n' + module + '\n  </script>'
    source, count = re.subn(r'<script data-optics-module="ray-tracing">.*?</script>', lambda _: replacement, source, flags=re.S)
    if count != 1:
        raise ValueError("Expected one ray module block")
    for name in ("pareto", "pareto-view"):
        module = (ROOT / "design" / (name + ".js")).read_text(encoding="utf-8")
        if "</script" in module.lower():
            raise ValueError("Module cannot contain an inline script terminator")
        replacement = '<script data-optics-module="' + name + '">\n// Generated by scripts/sync_preview_modules.py.\n' + module + '\n  </script>'
        source, count = re.subn(r'<script data-optics-module="' + name + '">.*?</script>',
                                lambda _: replacement, source, flags=re.S)
        if count != 1:
            raise ValueError("Expected one " + name + " module block")
    fixture = json.loads((ROOT / "design/ray-indices-fixture.json").read_text(encoding="utf-8"))
    encoded = json.dumps(fixture, ensure_ascii=True, separators=(",", ":"), allow_nan=False).replace("<", "\\u003c")
    replacement = "/* BEGIN RAY INDEX SNAPSHOT */\n    data.ray_indices=" + encoded + ";\n    /* END RAY INDEX SNAPSHOT */"
    source, count = re.subn(r'/\* BEGIN RAY INDEX SNAPSHOT \*/.*?/\* END RAY INDEX SNAPSHOT \*/', lambda _: replacement, source, flags=re.S)
    if count != 1:
        raise ValueError("Expected one ray metadata snapshot block")
    fragment.write_text(source, encoding="utf-8")
    return fragment


if __name__ == "__main__":
    print(sync())
